### ISSUE TITLE
connection problem with patch hpn-14.16 applied to openssh 7.9p1

### ISSUE THREAD

**Issue by mrbaseman** [rapier1/openssh-portable#18]
I know OpenSSH 7.9p1 is beyond the head of the commits in this repository and newer than what is offered on [sourceforge](https://sourceforge.net/projects/hpnssh/files/). Nevertheless I have tried to apply the patches to that version of openssh-portable. Patching went smooth and connections work mostly, except for a strange issue with some specific clients. 

OpenSSH_6.6.1 with OpenSSL 1.0.1e-fips on CentOS Linux release 7.2.1511 for instance hangs upon login with RSA key. 
The strange thing is that authentication works well, and even the motd is displayed but the prompt doesn't appear, and even killing the client with Ctrl+C doesn't work. 

The same patches applied to OpenSSH 7.8p1 work fine, with the same client, and even the client side debug log when connecting with -v -v only differs in version numbers, one time stamp and the pointer to the key, everything else looks exactly the same.

Any ideas what it could be or how to debug this problem?

**Comment by mrbaseman** [comment]
I forgot to mention that we don't see this problem with OpenSSH 7.9p1 without hpn patches, which makes it even stranger.

**Comment by rapier1** [comment]
Not strange at all because in OpenSSH everything is complicated. I can't 
think of anything specific at this point but it could be an issue with 
STDIN|OUT being handed off after the MOTD. It could also be a failure on 
the part of the patched version finding a necessary shell/shellrc.

I appreciate the heads up on this. I don't think I'll have time to focus 
on this for a few weeks though - preholiday crunch and all. I'll 
dedicate a few days to this issue as soon as I can though.

Chris

**Comment by mrbaseman** [comment]
Hi Chris

thanks for your reply. We went back to `openssh 7.8p1 hpn 14.16` in the meantime, and received the feedback from our user that it sometimes works and sometimes not. Until now we thought that the problem was introduced by applying the 14.16 patch to the latest openssh release, but now it seems that it was just not noticed (or not reported?) before and got worse... That sounds difficult to debug, maybe a race condition between the threads?

Let me know if we can provide anything that is helpful  for debugging.

Martin
