### ISSUE TITLE
Java clients

### ISSUE THREAD

**Issue by conorgriffin** [rapier1/openssh-portable#30]
This is a bit of a shot in the dark, but I've read your papers/presentations and justification for HPN-SSH and I'd love to use it, but we're bound at the moment to using a Java library.  At the moment I'm using JScape but it's not performing very well compared to openssh and so I'm going to evaluate alternatives.  Are you aware of any Java libraries that endeavour to do what you've done with HPN-SSH?  Or which Java SSH libraries are best for high throughput?  Many thanks for your time if you get a chance to respond.  Otherwise good luck with the new funding, I'll be watching this space with interest.

Conor

**Comment by rapier1** [comment]
Take a look at http://www.jcraft.com/jsch/. They say they support None 
Cipher Switching which is part of the HPN-SSH enhancements. I'ver never 
used it so I can't give you any idea of it's performance characteristics 
or usage.

**Comment by rapier1** [comment]
Also, if it doesn't implement dynamic receive buffers you may be able to statically define large buffers - which will help with bulk data transport. You'll need to dig through the source code to find the variable definition that they are using for that. It *may* be obvious but my guess is that the buffer will be defined to either 64K or 2048K. If you redefine it to something like 32MB that could help with inbound transfers. It may screw up interactive sessions with over buffering issues.

I don't know java all that well so I don't even know if the kernel parameters (like the tcp connections receive buffer) is available to the JVM. Sorry I can't be of more help on this.

**Comment by conorgriffin** [comment]
Yeah Jsch is one I'm going to check out thanks.  The one I'm using right now has a default download buffer of 32K and only a single outstanding request!  They do allow you to enable "pipelining" where you can have multiple parallel requests and their default is 8.  This is still almost 10x slower than vanilla sftp/openssh.  Upping the the buffer to 64K improves things a little, but going beyond that results in truncated files being 'successfully' downloaded, i.e. the transfer succeeds and doesn't throw any errors but the file is incomplete 🤷 .  Also, upping the number of parallel requests seems to offer no improvement once you go above 10.

Anyway, I'm going to experiment with a few libraries that allow these settings to be manipulated and see how the performance compares.  Thanks for your time. 🍻

**Comment by rapier1** [comment]
Best of luck. I also guess I should reach out to some of these 
developers at some point.

Chris

**Comment by jgoldverg** [comment]
Hello so I was planning on opening a similar request, about if there could be plans to write a Java client? 
I could even potentially consider as I have the immense need for a stable, and performance oriented SSH/SCP/SFTP client. Sadly Java is missing alternatives to [JSch](http://www.jcraft.com/jsch/). SSHJ is of worthy note as it has attempted to do this but the performance of that library is way below JSch.

Currently the Java community in general is stuck using JSch as the only SSH/SCP/SFTP client and it has massive limitations and has not been properly kept up to date as the last update to the [Maven Repository](https://mvnrepository.com/artifact/com.jcraft/jsch/0.1.55) was in 2018!

@conorgriffin in my experience [JSch](http://www.jcraft.com/jsch/) does perform well(when compared to rclone doing an Sftp transfer) but due to the massive lack of documentation the library becomes very difficult to tune.

**Comment by rapier1** [comment]
Honestly, that would be a heavy lift as it would essentially be rewriting large portions of HPN-SSH in Java - which is not a language I have much experience with. I would love to work with someone on it but I am not the right person to do it myself. That said, it may be possible use libssh.a with JNI to get started but that's mostly me just thinking out loud.

**Comment by jgoldverg** [comment]
Personally I do come from the Java background which is why I would feel ok in attempting to take this on but I would like to first say what I am looking for and what kind of roadmap we could strike up.

My use case, is I want to use the HPN ssh client in Java to communicate to openssh and hpn ssh servers to send large files over hpn's sftp and scp and obviously hopefully have higher throughput's closer to the link capacity.

From my trivial understanding of the project I would only need the client to fundamentally keep doing sftp, scp transfers but to saturate(lets say a chameleon cloud node with a 10Gb link) the link the HPN ssh server is required on the destination end correct or both client and destination?

In my usecase of saturating links on the client end then I would only need to port the client to Java correct?

**Comment by tomaswolf** [comment]
Java discussions are probably a bit out of place here, but nevertheless: the original JSch 0.1.55 is long abandoned. It does not support modern keys (no ed25519, for instance). It also has numerous bugs.

There is a [fork](https://github.com/mwiede/jsch) which fixed some bugs, added support for modern keys, and lots of other things. But it's still JSch, and it has inherited some of JSch's nasty bugs.

That said: JSch is not the only Java library for SSH. There is, for instance, [Apache MINA sshd](https://github.com/apache/mina-sshd). It's not perfect either, but works well and is an actively maintained open-source project of the ASF.
